# site/blueprints/pages/product.yml
title: Product
icon: 📦

status:
  draft: Draft
  listed: Published

options:
  changeSlug: true
  changeStatus: true
  duplicate: true

sections:
  # Basic product information section
  basicInfo:
    headline: Basic Information
    type: fields
    fields:
      productTitle:
        label: Product Title
        type: text
        required: true
        width: 2/3
      
      productId:
        label: Product ID/SKU
        type: text
        required: true
        help: Unique identifier for this product
        width: 1/3
      
      productType:
        label: Product Type
        type: tags
        max: 1
        width: 1/2
      
      productManufacturer:
        label: Manufacturer
        type: text
        width: 1/2
      
      productDetails:
        label: Product Details
        type: markdown
        size: large
      
      productRatingScore:
        label: Rating
        type: number
        min: 0
        max: 5
        step: 0.1
        before: ★
        width: 1/4
      
      categories:
        label: Categories
        type: pages
        query: site.find('categories').children
        multiple: true
      
      tags:
        label: Tags
        type: tags
  
  # Pricing and promotion section
  pricing:
    headline: Pricing & Promotions
    type: fields
    fields:
      priceOriginal:
        label: Original Price
        type: number
        step: 0.01
        before: $
        width: 1/3
        required: true
      
      productPromotion:
        label: On Sale
        type: toggle
        text: 
          - No
          - Yes
        width: 1/3
      
      discountPercentage:
        label: Discount %
        type: number
        min: 0
        max: 100
        step: 1
        after: "%"
        width: 1/3
        when:
          productPromotion: true
      
      priceNow:
        label: Current Price
        type: number
        step: 0.01
        before: $
        width: 1/2
        help: Leave blank to auto-calculate from discount percentage
        when:
          productPromotion: true
      
      savingAmt:
        label: Savings Amount
        type: info
        text: "{{ page.priceOriginal.toFloat - page.priceNow.toFloat }}$"
        width: 1/2
        when:
          productPromotion: true
      
      promotionStart:
        label: Promotion Start
        type: date
        time: true
        width: 1/2
        when:
          productPromotion: true
      
      promotionEnd:
        label: Promotion End
        type: date
        time: true
        width: 1/2
        when:
          productPromotion: true
  
  # Media section for product images
  media:
    headline: Product Images
    type: fields
    fields:
      productPhotographPrimary:
        label: Primary Product Image
        type: files
        layout: cards
        max: 1
        required: true
        uploads:
          template: image
      
      productPhotographMore:
        label: Additional Product Images
        type: files
        layout: cards
        uploads:
          template: image