# site/blueprints/pages/product.yml
title: Base Product
icon: box

status:
  draft: Draft
  listed: Published

options:
  changeSlug: true
  changeStatus: true
  duplicate: true

fields:
  product_id:
    label: Product ID
    type: text
    width: 1/2
    required: true
  
  name:
    label: Product Name
    type: text
    width: 1/2
    required: true
  
  description:
    label: Description
    type: textarea
    size: medium
  
  # Pricing section
  pricing:
    label: Pricing
    type: headline
  
  price:
    label: Regular Price
    type: number
    step: 0.01
    before: $
    width: 1/3
    required: true
  
  on_sale:
    label: On Sale
    type: toggle
    text: 
      - No
      - Yes
    width: 1/3
  
  sale_price:
    label: Sale Price
    type: number
    step: 0.01
    before: $
    width: 1/3
    when:
      on_sale: true
  
  discount_type:
    label: Discount Type
    type: select
    options:
      special: Special Offer
      clearance: Clearance
      seasonal: Seasonal Discount
      bundle: Bundle Deal
      loyalty: Loyalty Discount
    width: 1/2
    when:
      on_sale: true
  
  discount_label:
    label: Discount Label
    type: text
    placeholder: "e.g., 'Save 20%' or 'Weekly Special'"
    width: 1/2
    when:
      on_sale: true
  
  discount_description:
    label: Discount Explanation
    type: textarea
    size: small
    placeholder: "Explain the discount, e.g., 'Members save an extra 5% on all dairy products this week'"
    when:
      on_sale: true
  
  discount_valid_until:
    label: Discount Valid Until
    type: date
    width: 1/2
    when:
      on_sale: true
  
  # Stock info
  stock:
    label: Stock Amount
    type: number
    min: 0
    width: 1/3
  
  category:
    label: Category
    type: select
    options: query
    query: 
      fetch: site.categories.toStructure
      text: "{{ structureItem.title }}"
      value: "{{ structureItem.id }}"
    width: 1/3
  
  featured:
    label: Featured Product
    type: toggle
    text: 
      - No
      - Yes
    width: 1/2
  
  # Images
  main_image:
    label: Main Product Image
    type: files
    max: 1
    layout: cards
    required: true
  
  gallery:
    label: Additional Images
    type: files
    layout: cards