title: Dashboard

sections:
  # Research Studies heading
  kanbanHeading:
    type: fields
    class: studies-section-heading
    fields:
      mainHeading:
        label: Studies
        type: headline
        numbered: false
  
  # Your three studies sections kept together for CSS targeting
  upcomingStudies:
    headline: Upcoming 
    type: pages
    template: study
    status: listed
    create: false
    limit: 6
    empty: No upcoming studies
    layout: cardlets
    size: small
    info: "Starts: {{ page.startDate.toDate('M j') }}"
    filters:
      workflow: upcoming

  activeStudies:
    headline: Active 
    type: pages
    template: study
    status: listed
    create: false
    limit: 6
    empty: No active studies
    layout: cardlets
    size: small
    info: "Until: {{ page.endDate.toDate('M j') }}"
    filters:
      workflow: active    

  completedStudies:
    headline: Completed 
    type: pages
    template: study
    status: listed
    create: false
    limit: 6
    empty: No completed studies
    layout: cardlets
    size: small
    info: "Ended: {{ page.endDate.toDate('M j, Y') }}"
    filters:
      workflow: completed    
  
  # Divider and Resources heading
  resourcesDivider:
    type: fields
    fields:
      dividerLine:
        type: line
  
  # Resources section with columns
  resources:
    type: fields
    fields:
      resourcesHeading:
        label: Workbench
        type: headline
        size: h2

  
  # Individual resources sections - no columns
  wipStudies:
    headline: Works in progress
    type: pages
    template: study
    status: draft, unlisted
    sortBy: status desc modified desc
    create: 
      - study
    limit: 6
    empty: Create a new study
    layout: cardlets
    size: tiny

  collections:
    headline: Product Categories
    type: pages
    template: category
    create:
      - category
    limit: 6
    empty: No product categories found

  storefronts:
    headline: Storefront UIs
    type: pages
    template: storefront
    create:
      - storefront
    limit: 6
    empty: No storefronts found
        
