title: Dashboard

sections:
  # Research Studies heading
  kanbanHeading:
    type: fields
    class: studies-section-heading
    fields:
      mainHeading:
        label: Studies
        type: headline
        numbered: false
  
  # Your three studies sections kept together for CSS targeting
  upcomingStudies:
    headline: Upcoming studies
    type: pages
    template: study
    create: false
    limit: 6
    empty: No upcoming studies
    layout: cards
    size: small

  activeStudies:
    headline: Active studies
    type: pages
    template: study
    create: false
    limit: 6
    empty: No active studies
    layout: cards
    size: small

  completedStudies:
    headline: Completed studies
    type: pages
    template: study
    create: false
    limit: 6
    empty: No completed studies
    layout: cards
    size: small
  
  # Divider and Resources heading
  resourcesDivider:
    type: fields
    fields:
      dividerLine:
        type: line
  
  # Resources section with columns
  resources:
    type: fields
    fields:
      resourcesHeading:
        label: Workbench
        type: headline
        size: h2

  
  # Individual resources sections - no columns
  wipStudies:
    headline: Draft studies
    type: pages
    template: study
    create: 
      - study
    limit: 6
    empty: Create a new study
    layout: cards
    size: small

  collections:
    headline: Product collections
    type: pages
    template: collections
    create:
      - collection
    limit: 6
    empty: No product collections found

  storefronts:
    headline: Storefront UIs
    type: pages
    template: storefront
    create:
      - storefront
    limit: 6
    empty: No storefronts found
        
