title: Dashboard

sections:
  kanbanHeading:
    type: info
    headline: Research Studies
    text: Manage your research studies workflow
    
  upcomingStudies:
    headline: Upcoming Studies
    type: pages
    template: study
    create:
      - study
    empty: No upcoming studies
    layout: cards
    size: small

  activeStudies:
    headline: Active Studies
    type: pages
    template: study
    empty: No active studies
    layout: cards
    size: small

  completedStudies:
    headline: Completed Studies
    type: pages
    template: study
    empty: No completed studies
    layout: cards
    size: small
  
  resourcesHeading:
    type: info
    headline: Resources
    text: Manage product categories and storefront templates

columns:
  - width: 1/3
    sections:
      categories:
        headline: Product Categories
        type: pages
        template: category
        create:
          - category
        empty: No categories found

  - width: 1/3
    sections:
      storefronts:
        headline: Storefront UIs
        type: pages
        template: storefront
        create:
          - storefront
        empty: No storefronts found
        
  - width: 1/3
    sections:
      # Reserved for future use
      placeholderSection:
        type: info
        headline: Future Section
        text: This space is reserved for future functionality